# Generated by Django 3.0.1 on 2019-12-27 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=511)),
                ('weight_g', models.IntegerField()),
                ('size_cubic_cm', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
