# Generated by Django 3.0.1 on 2019-12-27 18:00

from django.db import migrations, models
import django.db.models.deletion
import subscription.models.subscription
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_date', models.DateField(default=None, help_text='Calendar date when this subscription should be billed. If `None`, it is considered inactive.', null=True)),
                ('bill_frequency', models.CharField(choices=[(subscription.models.subscription.BillFrequencyEnum['MONTH'], 'month'), (subscription.models.subscription.BillFrequencyEnum['DAY'], 'day'), (subscription.models.subscription.BillFrequencyEnum['WEEK'], 'week')], default='MONTH', help_text='How the bill_interval be measured', max_length=31)),
                ('bill_interval', models.IntegerField(default=1, help_text='How many e.g. days, weeks, months until this subscription should be billed')),
                ('box_type_preference', models.ForeignKey(help_text='The abstract type of box which should be delivered every interval.', on_delete=django.db.models.deletion.PROTECT, to='box.BoxType')),
                ('customer', models.ForeignKey(help_text='The person who should be billed for this subscription', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('next_box', models.ForeignKey(default=None, help_text='The instance of the next box to be delivered to this subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='box.Box')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
